spring:
  data:
    mongodb:
      uri: mongodb+srv://amirholya01:amir1365@cluster0.yroiiwj.mongodb.net/amir_final_exam_db?retryWrites=true&w=majority&appName=Cluster0


amir:
  app:
    jwtSecretKey: FrauGucciSecretKey
    jwtExpirationMs: 864000000
  file:
    extension: mp4, mkv, webm, mpg, 3gp, avi, tc